# Generated by Django 4.2 on 2023-04-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Кыргызстан', 'Кыргызстан')], max_length=10)),
                ('region', models.CharField(choices=[('Бишкек', 'Бишкек'), ('Чуй', 'Чуй'), ('Каракол', 'Каракол'), ('Баткен', 'Баткен'), ('Джалал-Абад', 'Джалал-Абад'), ('Нарын', 'Нарын'), ('Талас', 'Талас'), ('Ош', 'Ош')], max_length=11)),
                ('date', models.DateField()),
                ('name_competitions', models.CharField(max_length=255)),
                ('name_organizer', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('telegram', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('age_groups_of_participants', models.CharField(choices=[('до 18', 'до 18'), ('18-25', '18-25'), ('25-35', '25-35'), ('35-45', '35-45'), ('A, B, C, D', 'A, B, C, D ')], max_length=255)),
                ('illustration', models.ImageField(upload_to='media/')),
                ('announcement', models.TextField()),
                ('Link_to_competition', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
