# Generated by Django 4.2 on 2023-04-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_alter_competition_illustration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Соревнование', 'verbose_name_plural': 'Соревнования'},
        ),
    ]
