# Generated by Django 4.2 on 2023-04-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_competition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='Link_to_competition',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на положение о соревнованиях'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='age_groups_of_participants',
            field=models.CharField(choices=[('до 18', 'до 18'), ('18-25', '18-25'), ('25-35', '25-35'), ('35-45', '35-45'), ('A, B, C, D', 'A, B, C, D ')], max_length=255, verbose_name='Возрастные группы участников'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='announcement',
            field=models.TextField(verbose_name='Краткий анонс'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.DateField(verbose_name='Дата (-ы) проведения'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='illustration',
            field=models.ImageField(upload_to='media', verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name_competitions',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='region',
            field=models.CharField(choices=[('Бишкек', 'Бишкек'), ('Чуй', 'Чуй'), ('Каракол', 'Каракол'), ('Баткен', 'Баткен'), ('Джалал-Абад', 'Джалал-Абад'), ('Нарын', 'Нарын'), ('Талас', 'Талас'), ('Ош', 'Ош')], max_length=11, verbose_name='Регион проведения'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='state',
            field=models.CharField(choices=[('Кыргызстан', 'Кыргызстан')], max_length=10, verbose_name='Государство проведения'),
        ),
    ]
