# Generated by Django 4.2 on 2023-05-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_competition_link_to_competition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='coordinates_to_competition',
            field=models.CharField(blank=True, max_length=255, verbose_name='Точные координаты'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='illustration',
            field=models.ImageField(upload_to='tidi', verbose_name='Иллюстрация'),
        ),
    ]
