# Generated by Django 4.2 on 2023-05-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_alter_competition_illustration_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='Link_to_competition',
        ),
    ]
