# Generated by Django 4.2 on 2023-05-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_remove_competition_link_to_competition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='name_competitions',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='email',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='name_organizer',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='whatsapp',
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organizer', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('telegram', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=255)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
            ],
        ),
    ]
