# Generated by Django 4.2 on 2023-05-17 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_rename_name_competitions_competition_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='name',
            new_name='name_competition',
        ),
        migrations.AlterField(
            model_name='organizer',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition'),
        ),
    ]
