# Generated by Django 4.2 on 2023-05-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_rename_name_competition_name_competition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizer',
            options={'verbose_name': 'Организатор', 'verbose_name_plural': 'Организаторы'},
        ),
        migrations.AlterField(
            model_name='organizer',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizers', to='competitions.competition'),
        ),
    ]
