# Generated by Django 4.2 on 2023-05-18 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_alter_organizer_options_alter_organizer_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='competitions.competition'),
        ),
    ]
