# Generated by Django 4.2 on 2023-05-22 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0014_alter_organizer_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
    ]
