# Generated by Django 4.2 on 2023-05-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_competition_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email организатора'),
        ),
        migrations.AddField(
            model_name='competition',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия организатора'),
        ),
        migrations.AddField(
            model_name='competition',
            name='name_organizer',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя организатора'),
        ),
        migrations.AddField(
            model_name='competition',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='номер телефона организатора'),
        ),
        migrations.AddField(
            model_name='competition',
            name='telegram',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
