# Generated by Django 4.2 on 2023-05-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_competition_email_competition_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='name_competition',
            new_name='competition_name',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='email',
            new_name='organizer_email',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='last_name',
            new_name='organizer_last_name',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='name_organizer',
            new_name='organizer_name',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='phone',
            new_name='organizer_phone',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='telegram',
            new_name='organizer_telegram',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='whatsapp',
            new_name='organizer_whatsapp',
        ),
    ]
