# Generated by Django 4.2 on 2023-05-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0020_alter_competition_organizer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
