# Generated by Django 4.2.2 on 2023-06-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0022_alter_competition_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='age_groups_of_participants',
            field=models.CharField(max_length=255, verbose_name='Возрастные группы участников'),
        ),
    ]
