# Generated by Django 4.2 on 2023-04-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_competitions', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('discharge', models.CharField(max_length=50)),
                ('team', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
