# Generated by Django 4.2 on 2023-04-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Участника', 'verbose_name_plural': 'Участники'},
        ),
    ]
