# Generated by Django 4.2.2 on 2023-06-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_member_name_competitions_member_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=1, null=True, verbose_name='Пол'),
        ),
    ]
