# Generated by Django 4.2.2 on 2023-06-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age_group',
            field=models.CharField(blank=True, max_length=3, verbose_name='Возрастная группа'),
        ),
    ]
