# Generated by Django 4.2.2 on 2023-06-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age_group',
            field=models.CharField(blank=True, max_length=10, verbose_name='Возрастная группа'),
        ),
    ]
