# Generated by Django 4.2 on 2023-05-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Доп-инфа пользователей', 'verbose_name_plural': 'Доп-инфа пользователя'},
        ),
    ]
