# Generated by Django 4.2 on 2023-05-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usergroup_can_add_comments_usergroup_can_view_pages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
