# Generated by Django 4.2 on 2023-05-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Photo',
            field=models.ImageField(default=1, upload_to='user_photo'),
            preserve_default=False,
        ),
    ]
