# Generated by Django 4.2 on 2023-06-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_profile_status_profile_is_blocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Photo',
            new_name='photo',
        ),
    ]
